In [71]:
from load_recommender_data import load_recommender_data

df_merge, anime_df, user_df =  load_recommender_data('user_data1.0.json')
df_merge.head()

/home/dipesh/repositories/Codagami_Anime_Recommender/load_recommender_data.py:27: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  user_df = melt_series(df.data).to_frame().join(df.drop('data', 1))
/home/dipesh/repositories/Codagami_Anime_Recommender/env/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
/home/dipesh/repositories/Codagami_Anime_Recommender/load_recommender_data.py:79: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

anime_id          name                                              genre  \
0       1.0  Cowboy Bebop  [Action, Adventure, Comedy, Drama, Sci-Fi, Space]   
1       1.0  Cowboy Bebop  [Action, Adventure, Comedy, Drama, Sci-Fi, Space]   
2       1.0  Cowboy Bebop  [Action, Adventure, Comedy, Drama, Sci-Fi, Space]   
3       1.0  Cowboy Bebop  [Action, Adventure, Comedy, Drama, Sci-Fi, Space]   
4       1.0  Cowboy Bebop  [Action, Adventure, Comedy, Drama, Sci-Fi, Space]   

   episodes  rating_x  members  user_id  rating_y  
0      26.0         8  1488371        1         0  
1      26.0         8  1488371        2         7  
2      26.0         8  1488371        3        10  
3      26.0         8  1488371        5         8  
4      26.0         8  1488371        6        10

In [47]:
# df_merge.sort_values('rating_x', ascending=False)

anime_id                              name  \
4986     5114.0  Fullmetal Alchemist: Brotherhood   
30425    9253.0                       Steins;Gate   
46476   39486.0                Gintama: The Final   
7544    11061.0            Hunter x Hunter (2011)   
7545    11061.0            Hunter x Hunter (2011)   
...         ...                               ...   
32501   13405.0                Utsu Musume Sayuri   
4125     3287.0      Tenkuu Danzai Skelter+Heaven   
4122     3287.0      Tenkuu Danzai Skelter+Heaven   
32498   13405.0                Utsu Musume Sayuri   
4121     3287.0      Tenkuu Danzai Skelter+Heaven   

                                                   genre  episodes  rating_x  \
4986   [Action, Adventure, Comedy, Drama, Fantasy, Mi...      64.0         9   
30425           [Drama, Psychological, Sci-Fi, Suspense]      24.0         9   
46476  [Action, Comedy, Drama, Historical, Parody, Sa...       1.0         9   
7544   [Action, Adventure, Fantasy, Shounen, Super Po...     148.0         9   
7545   [Action, Adventure, Fantasy, Shounen, Super Po...     148.0         9   
...                                                  ...       ...       ...   
32501                              [Avant Garde, Comedy]       1.0         1   
4125                                     [Mecha, Sci-Fi]       1.0         1   
4122                                     [Mecha, Sci-Fi]       1.0         1   
32498                              [Avant Garde, Comedy]       1.0         1   
4121                                     [Mecha, Sci-Fi]       1.0         1   

       members  user_id  rating_y  
4986   2683548       81         9  
30425  2096521       58         0  
46476    80276       50         8  
7544   2158236        0         8  
7545   2158236        1        10  
...        ...      ...       ...  
32501    17154       95         1  
4125     30978       92         0  
4122     30978       48         2  
32498    17154       23         5  
4121     30978        1         1  

[49730 rows x 8 columns]

In [48]:
# anime_df.head()

anime_id                   title  mean  num_episodes  \
1        1.0            Cowboy Bebop  8.77          26.0   
6        6.0                  Trigun  8.22          26.0   
8        8.0          Bouken Ou Beet  6.96          52.0   
16      16.0    Hachimitsu to Clover  8.03          24.0   
18      18.0  Initial D Fourth Stage  8.14          24.0   

                                          genres_name             genres_id  \
1   [Action, Adventure, Comedy, Drama, Sci-Fi, Space]  [1, 2, 4, 8, 24, 29]   
6   [Action, Adventure, Comedy, Drama, Sci-Fi, Sho...  [1, 2, 4, 8, 24, 27]   
8         [Adventure, Fantasy, Shounen, Supernatural]       [2, 10, 27, 37]   
16     [Comedy, Drama, Josei, Romance, Slice of Life]    [4, 8, 43, 22, 36]   
18              [Action, Cars, Drama, Seinen, Sports]     [1, 3, 8, 42, 30]   

   watching  num_list_users completed plan_to_watch dropped on_hold  
1    137020         1488371    837883        397985   31587   83896  
6     33591          624343    375886        171194   15445   28227  
8       679           13904      7588          3695    1150     792  
16    13026          234999     85960        111377   11903   12733  
18     7408          140358    107001         20731    1588    3630

In [49]:
# user_df.head()

user  user_id  anime_id     status  user_score  is_rewatching
0  chinmay453        0     38101  completed           8          False
0  chinmay453        0     32998  completed           8          False
0  chinmay453        0     34881  completed           7          False
0  chinmay453        0     22199  completed          10          False
0  chinmay453        0        47  completed           0          False

In [72]:
import numpy as np
import pandas as pd

In [73]:
df_merge.dtypes

anime_id    float64
name         object
genre        object
episodes    float64
rating_x      int64
members       int64
user_id       int64
rating_y      int64
dtype: object

In [74]:
df_merge['anime_id'] = df_merge['anime_id'].astype(np.int32)
df_merge['rating_x'] = df_merge['rating_x'].astype(np.int32)
df_merge['user_id'] = df_merge['user_id'].astype(np.int32)
df_merge = df_merge[['anime_id', 'rating_x','user_id']]
df_merge.dtypes

anime_id    int32
rating_x    int32
user_id     int32
dtype: object

In [75]:
df_merge = df_merge.sample(n=5)
df_merge

anime_id  rating_x  user_id
37629     28851         8       34
10856     21561         7       83
13604     30925         7       23
3075       1690         7       86
4168       3367         6       39

In [82]:

ratings_mat = np.ndarray(
    shape=(np.max(df_merge.anime_id.values), np.max(df_merge.user_id.values)+1),
    dtype=np.uint8)
ratings_mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [84]:
ratings_mat[df_merge.anime_id.values-1, df_merge.user_id.values] = df_merge.rating_x.values
ratings_mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [85]:
normalised_mat = ratings_mat - np.asarray([(np.mean(ratings_mat, 1))]).T
normalised_mat

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.08045977, -0.08045977, -0.08045977, ..., -0.08045977,
        -0.08045977, -0.08045977]])

In [86]:
A = normalised_mat.T / np.sqrt(ratings_mat.shape[0] - 1)
A

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00045754]])

In [87]:
U, S, V = np.linalg.svd(A)

In [ ]:
def top_cosine_similarity(data, anime_id, top_n=10):
    index = anime_id - 1 # Movie id starts from 1 in the dataset
    movie_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[:top_n]

In [ ]:
def print_similar_movies(anime_df, anime_id, top_indexes):
    print('Recommendations for {0}: \n'.format(
    anime_df[anime_df.anime_id == anime_id].title.values[0]))
    for id in top_indexes + 1:
        print(anime_df[anime_df.anime_id == id].title.values[0])

In [ ]:
k = 50
anime_id = 10 # (getting an id from movies.dat)
top_n = 10
sliced = V.T[:, :k] # representative data
indexes = top_cosine_similarity(sliced, anime_id, top_n)

#Printing the top N similar movies
print_similar_movies(anime_df, anime_id, indexes)

NameError: name 'V' is not defined